RTFProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('students/', include('students.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

students/urls.py
from django.contrib import admin
from django.urls import path, include

from students.views import all_students, student, create_student, edit_student

app_name = "students"

urlpatterns = [
    path('allStudents/', all_students, name='all_students'),
    path('student/<int:pk>/', student, name='student'),
    path('createStudent', create_student, name='create_student'),
    path('editStudent/<int:pk>/', edit_student, name='edit_student'),
]

students/models.py
from django.db import models


class FinancingForm(models.Model):
    title = models.CharField(max_length=255)

    class Meta:
        verbose_name = "Форма финансирования"
        verbose_name_plural = "Формы финансирования"

    def __str__(self):
        return self.title


class EducationStage(models.Model):
    title = models.CharField(max_length=255)

    class Meta:
        verbose_name = "Ступень образования"
        verbose_name_plural = "Ступень образования"

    def __str__(self):
        return self.title


class EducationForm(models.Model):
    title = models.CharField(max_length=255)

    class Meta:
        verbose_name = "Форма обучения"
        verbose_name_plural = "Формы обучения"

    def __str__(self):
        return self.title


class Specialization(models.Model):
    title = models.CharField(max_length=255)

    class Meta:
        verbose_name = "Специальность"
        verbose_name_plural = "Специальности"

    def __str__(self):
        return self.title


class Citizenship(models.Model):
    title = models.CharField(max_length=255)

    class Meta:
        verbose_name = "Гражданство"
        verbose_name_plural = "Гражданства"

    def __str__(self):
        return self.title


class Student(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    patronymic = models.CharField(max_length=255, blank=True, null=True)
    phone_number = models.CharField(max_length=12, blank=True, null=True)
    email = models.EmailField(max_length=255, blank=True, null=True)
    birth_date = models.DateField(blank=True, null=True)
    start_education_date = models.IntegerField(blank=True, null=True)
    end_education_date = models.IntegerField(blank=True, null=True)
    living_place = models.CharField(max_length=255, blank=True, null=True)
    is_deleted = models.BooleanField(default=False)
    added_date = models.DateTimeField(auto_now_add=True)
    group = models.CharField(max_length=255, blank=True, null=True)

    specialization = models.ForeignKey(Specialization, on_delete=models.SET_NULL, null=True)
    education_form = models.ForeignKey(EducationForm, on_delete=models.SET_NULL, blank=True, null=True)
    education_stage = models.ForeignKey(EducationStage, related_name='education_stage', on_delete=models.SET_NULL, blank=True, null=True)
    financing_form = models.ForeignKey(FinancingForm, on_delete=models.SET_NULL, blank=True, null=True)
    citizenship = models.ForeignKey(Citizenship, on_delete=models.SET_NULL, blank=True, null=True)

    class Meta:
        verbose_name = "Студент"
        verbose_name_plural = "Студенты"
        ordering = ['first_name', '-start_education_date']

    def __str__(self):
        return f'{self.last_name} {self.first_name}'


class StudentParticipation(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    date = models.DateField(blank=True, null=True)
    student = models.ForeignKey(Student, verbose_name="Студент", related_name='student_participation', on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Студенческие активности"
        verbose_name_plural = "Студенческие активности"

    def __str__(self):
        return self.title


class Achievements(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    date = models.DateField(blank=True, null=True)
    student = models.ForeignKey(Student, verbose_name="Студент", related_name='achievements', on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Достижения"
        verbose_name_plural = "Достижение"

    def __str__(self):
        return self.title

students/forms.py
from django.forms import ModelForm
from .models import Student, Specialization, EducationForm, EducationStage, FinancingForm, Citizenship
from django.contrib.auth.forms import UserCreationForm
from django import forms


class CustomSelectWidget(forms.Select):
    template_name = 'students/custom_select_widget.html'


class StudentCreationForm(ModelForm):
    specialization = forms.CharField(required=False)
    education_form = forms.CharField(required=False)
    education_stage = forms.CharField(required=False)
    financing_form = forms.CharField(required=False)
    citizenship = forms.CharField(required=False)

    def clean_field(self, field_name, model_class):
        value = self.cleaned_data[field_name]

        if value:
            obj = model_class.objects.filter(title=value).first()
            if not obj:
                obj = model_class.objects.create(title=value)

            return obj
        return None

    def clean_specialization(self):
        return self.clean_field('specialization', Specialization)

    def clean_education_form(self):
        return self.clean_field('education_form', EducationForm)

    def clean_education_stage(self):
        return self.clean_field('education_stage', EducationStage)

    def clean_financing_form(self):
        return self.clean_field('financing_form', FinancingForm)

    def clean_citizenship(self):
        return self.clean_field('citizenship', Citizenship)

    class Meta:
        model = Student
        exclude = ['is_deleted']


class FilterForm(forms.Form):
    specialization = forms.ModelMultipleChoiceField(queryset=Specialization.objects.all(),
                                                    widget=forms.CheckboxSelectMultiple, to_field_name='title',
                                                    required=False)
    education_form = forms.ModelMultipleChoiceField(queryset=EducationForm.objects.all(),
                                                    widget=forms.CheckboxSelectMultiple, to_field_name='title',
                                                    required=False)
    education_stage = forms.ModelMultipleChoiceField(queryset=EducationStage.objects.all(),
                                                     widget=forms.CheckboxSelectMultiple, to_field_name='title',
                                                     required=False)

students/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView
from .models import Student, Specialization, EducationStage, EducationForm, FinancingForm, Citizenship
from students.forms import StudentCreationForm, FilterForm
from django.core.paginator import Paginator
from django.db.models import Q


@login_required
def all_students(request):
    students = Student.objects.all()
    form = FilterForm(request.GET)
    selected_filters = []

    if form.is_valid():
        specializations = form.cleaned_data['specialization']
        education_form = form.cleaned_data['education_form']
        education_stage = form.cleaned_data['education_stage']

        if specializations:
            students = students.filter(specialization__in=specializations)
            selected_filters += list(specializations)

        if education_form:
            students = students.filter(education_form__in=education_form)
            selected_filters += list(education_form)

        if education_stage:
            students = students.filter(education_stage__in=education_stage)
            selected_filters += list(education_stage)

    query = request.GET.get('query')

    if query:
        students = students.filter(
            Q(first_name__iregex=query) |
            Q(last_name__iregex=query) |
            Q(patronymic__iregex=query) |
            Q(end_education_date__iregex=query) |
            Q(group__iregex=query) |
            Q(specialization__title__iregex=query)
        )

    sort_option = request.GET.get('sort_option')

    if sort_option == 'inc_year':
        students = students.order_by('end_education_date')
    elif sort_option == 'dec_year':
        students = students.order_by('-end_education_date')
    elif sort_option == 'inc_last_name':
        students = students.order_by('last_name')

    paginator = Paginator(students, 10)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj, 'sort_option': sort_option, 'query': query, 'form': form,
        'selected_filters': selected_filters
    }

    return render(request, 'students/students_table.html', context)


@login_required
def student(request, pk):
    student = get_object_or_404(Student, id=pk)
    return render(request, 'students/student_profile.html', {'student': student})


@login_required
def create_student(request):
    if request.method == 'POST':
        form = StudentCreationForm(request.POST)

        if form.is_valid():
            student = form.save(commit=False)
            student.save()

            return redirect('students:all_students')
    else:
        form = StudentCreationForm()

    specializations = Specialization.objects.all()
    education_forms = EducationForm.objects.all()
    education_stages = EducationStage.objects.all()
    financing_forms = FinancingForm.objects.all()
    citizenships = Citizenship.objects.all()

    context = {
        'form': form, 'specializations': specializations, 'education_forms': education_forms,
        'education_stages': education_stages, 'financing_forms': financing_forms, 'citizenships': citizenships
    }

    return render(request, 'students/student_create.html', context)


@login_required
def edit_student(request, pk):
    student = get_object_or_404(Student, id=pk)

    if request.method == 'POST':
        form = StudentCreationForm(request.POST, instance=student)

        if form.is_valid():
            form.save()
            return redirect('students:all_students')
    else:
        form = StudentCreationForm(instance=student)

    specializations = Specialization.objects.all()
    education_forms = EducationForm.objects.all()
    education_stages = EducationStage.objects.all()
    financing_forms = FinancingForm.objects.all()
    citizenships = Citizenship.objects.all()

    context = {
        'form': form, 'student': student, 'specializations': specializations, 'education_forms': education_forms,
        'education_stages': education_stages, 'financing_forms': financing_forms, 'citizenships': citizenships
    }

    return render(request, 'students/student_edit.html', context)

students/templates/students/custom_select_widget.html
{% spaceless %}
    <input list="myList" name="education_stage">
    <datalist>
        {% for value in education_stages %}
            <option value="{{ value }}"></option>
        {% endfor %}
    </datalist>
{% endspaceless %}

students/templates/students/student_edit.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'styles/student_profile.css' %}">
    <link rel="stylesheet" href="{% static 'styles/header.css' %}">
    <title>Студенты</title>
</head>
<body>
<div class="web">

    <div class="header">
        <div class="container1">
            <div class="header-line1">
                <div class="header-logo">
                    <img class="logotype" src="{% static 'icons/URFU.png' %}" alt="">
                </div>
                <div class="nav">
                    <a class="nav-item1" href="{% url 'logout' %}">Выход</a>
                </div>
            </div>
        </div>
    </div>


    <div class="center">
        <div class="columns">
            <div class="left"></div>
            <div class="area">
                <div class="box-1">
                    <div>

                    </div>
                    <div class="edit">
                    </div>
                    <div class="back">
                        <a href="{% url 'students:student' student.id %}" class="btn btn-primary">
                            <button class="but_back">Назад</button>
                        </a>
                    </div>
                </div>
                <form method="post">
                    {% csrf_token %}
                    <div class="boxes">
                        <p class="full-box-title">Фамилия</p>
                        <input class="full_field" name="last_name"
                               value="{{ student.last_name }}"
                               required>

                        <p class="full-box-title">Имя</p>
                        <input class="full_field" name="first_name"
                               value="{{ student.first_name }}"
                               required>

                        <p class="full-box-title">Отчество</p>
                        <input class="full_field" name="patronymic"
                               value="{{ student.patronymic|default:'' }}"
                               required>

                        <div class="boxx-4-1">
                            <p class="full-box-title">Специальность</p>
                            <p class="full-box-title">Год выпуска</p>

                            <input class="full_field" list="specialization_list" name="specialization" {% if student.specialization %} value="{{ student.specialization }}" {% endif %}>
                            <datalist id="specialization_list">
                                {% for specialization in specializations %}
                                    <option value="{{ specialization }}"></option>
                                {% endfor %}
                            </datalist>
                            <input class="full_field" name="end_education_date"
                                   value="{{ student.end_education_date }}">
                        </div>


                        <p class="full-box-title">Номер телефона</p>
                        <input class="full_field" name="phone_number" value="{{ student.phone_number|default:'' }}">


                        <p class="full-box-title">Почта</p>
                        <input class="full_field" name="email" value="{{ student.email|default:'' }}">


                        <p class="full-box-title">Академическая группа</p>
                        <input class="full_field" name="group" value="{{ student.group|default:'' }}">


                        <p class="full-box-title">Форма обучения</p>
                        <input class="full_field" list="education_form_list" name="education_form" {% if student.education_form %} value="{{ student.education_form }}" {% endif %}>
                        <datalist id="education_form_list">
                            {% for education_form in education_forms %}
                                <option value="{{ education_form }}"></option>
                            {% endfor %}
                        </datalist>


                        <p class="full-box-title">Ступень образования</p>
                        <input class="full_field" list="education_stage_list" name="education_stage" {% if student.education_stage %} value="{{ student.education_stage }}" {% endif %}>
                        <datalist id="education_stage_list">
                            {% for education_stage in education_stages %}
                                <option value="{{ education_stage }}"></option>
                            {% endfor %}
                        </datalist>


                        <p class="full-box-title">Форма финансирования</p>
                        <input class="full_field" list="financing_form_list" name="financing_form" {% if student.financing_form %} value="{{ student.financing_form }}" {% endif %}>
                        <datalist id="financing_form_list">
                            {% for financing_form in financing_forms %}
                                <option value="{{ financing_form }}"></option>
                            {% endfor %}
                        </datalist>


                        <p class="full-box-title">Гражданство</p>
                        <input class="full_field" list="citizenship_list" name="citizenship" {% if student.citizenship %} value="{{ student.citizenship }}" {% endif %}>
                        <datalist id="citizenship_list">
                            {% for citizenship in citizenships %}
                                <option value="{{ citizenship }}"></option>
                            {% endfor %}
                        </datalist>

                        {{ form.errors }}

                        <div class="save-btn">
                            <button class="but_edit" type="submit">Сохранить</button>
                        </div>
                        {{ form.errors }}
                    </div>
                </form>
            </div>
            <div class="right"></div>
        </div>
    </div>
    <div class="footer">
        <div class="columns">
            <div class="foot_left"></div>
            <div class="foot_center">
                <p class="foot">
                    ©ФГАОУ ВО «УрФУ имени первого Президента России Б.Н.Ельцина»
                </p>
            </div>
            <div class="foot_right"></div>
        </div>
    </div>
</div>
</body>
</html>

students/templates/students/student_profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'styles/student_profile.css' %}">
    <link rel="stylesheet" href="{% static 'styles/header.css' %}">
    <title>Title</title>
</head>
<body>
<div class="web">

    <div class="header">
        <div class="container1">
            <div class="header-line1">
                <div class="header-logo">
                    <img class="logotype" src="{% static 'icons/URFU.png' %}" alt="">
                </div>
                <div class="nav">
                    <a class="nav-item1" href="{% url 'logout' %}">Выход</a>
                </div>
            </div>
        </div>
    </div>


    <div class="center">
        <div class="columns">
            <div class="left"></div>
            <div class="area">
                <div class="box-1">
                    <div>

                    </div>
                    <div class="edit">
                        <a href="{% url 'students:edit_student' student.id %}" class="btn btn-primary">
                            <button class="but_edit">Редактировать</button>
                        </a>
                    </div>
                    <div class="back">
                        <a href="{% url 'students:all_students' %}" class="btn btn-primary">
                            <button class="but_back">Назад</button>
                        </a>
                    </div>
                </div>

                <div class="boxes">
                    <p class="full-box-title">Фамилия</p>
                    <p class="full_field">{{ student.last_name }}</p>

                    <p class="full-box-title">Имя</p>
                    <p class="full_field">{{ student.first_name }}</p>

                    {% if student.patronymic %}
                        <p class="full-box-title">Отчество</p>
                        <p class="full_field">{{ student.patronymic }}</p>
                    {% endif %}

                    <div class="boxx-4-1">
                        <p class="full-box-title">Специальность</p>
                        <p class="full-box-title">Год выпуска</p>

                        <p class="full_field"> {{ student.specialization }}</p>
                        <p class="full_field">{{ student.end_education_date }}</p>
                    </div>

                    {% if student.phone_number %}
                        <p class="full-box-title">Номер телефона</p>
                        <p class="full_field">{{ student.phone_number }}</p>
                    {% endif %}

                    {% if student.email %}
                        <p class="full-box-title">Почта</p>
                        <p class="full_field">{{ student.email }}</p>
                    {% endif %}


                    {% if student.group %}
                        <p class="full-box-title">Академическая группа</p>
                        <p class="full_field">{{ student.group }}</p>
                    {% endif %}

                    {% if student.education_form %}
                        <p class="full-box-title">Форма обучения</p>
                        <p class="full_field">{{ student.education_form }}</p>
                    {% endif %}

                    {% if student.education_stage %}
                        <p class="full-box-title">Ступень образования</p>
                        <p class="full_field">{{ student.education_stage }}</p>
                    {% endif %}

                    {% if student.financing_form %}
                        <p class="full-box-title">Форма финансирования</p>
                        <p class="full_field">{{ student.financing_form }}</p>
                    {% endif %}

                    {% if student.citizenship %}
                        <p class="full-box-title">Гражданство</p>
                        <p class="full_field">{{ student.citizenship }}</p>
                    {% endif %}

                    {% if student.added_date %}
                        <p class="full-box-title">Дата добавления</p>
                        <p class="full_field">{{ student.added_date }}</p>
                    {% endif %}

                </div>
            </div>
            <div class="right"></div>
        </div>
    </div>

    <div class="footer">
        <div class="columns">
            <div class="foot_left"></div>
            <div class="foot_center">
                <p class="foot">
                    ©ФГАОУ ВО «УрФУ имени первого Президента России Б.Н.Ельцина»
                </p>
            </div>
            <div class="foot_right"></div>
        </div>
    </div>
</div>
</body>
</html>

students/templates/students/students_table.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'styles/new_style.css' %}">
    <link rel="stylesheet" href="{% static 'styles/header.css' %}">
    <title>Студенты</title>
</head>
<body>

<div class="header">
    <div class="container1">
        <div class="header-line1">
            <div class="header-logo">
                <img class="logotype" src="{% static 'icons/URFU.png' %}" alt="">
            </div>
            <div class="nav">
                <a class="nav-item1" href="{% url 'logout' %}">Выход</a>
            </div>
        </div>
    </div>
</div>
<form id="sort-form" method="GET" action="{% url 'students:all_students' %}">
    <div class="container">

        <div class="left_table">
            <div></div>
            <div></div>
            <div class="naming_filter">
                <p class="label-title">Поиск по фильтрам</p>
            </div>

            <div class="dropdown-checkbox form-group">
                <p class="label-title">Специальность</p>
                <ul>
                    {% for cat in form.specialization.field.queryset %}
                        <li><label><input type="checkbox" name="specialization" value="{{ cat.title }}"
                                          {% if cat in selected_filters %}checked="checked"{% endif %}>{{ cat.title }}
                        </label></li>
                    {% endfor %}
                </ul>
            </div>

            <div class="dropdown-checkbox form-group">
                <p class="label-title">Форма обучения</p>
                <ul>
                    {% for cat in form.education_form.field.queryset %}
                        <li><label><input type="checkbox" name="education_form" value="{{ cat.title }}"
                                          {% if cat in selected_filters %}checked="checked"{% endif %}>{{ cat.title }}
                        </label></li>
                    {% endfor %}
                </ul>
            </div>

            <div class="dropdown-checkbox form-group">
                <p class="label-title">Ступень обучения</p>
                <ul>
                    {% for cat in form.education_stage.field.queryset %}
                        <li><label><input type="checkbox" name="education_stage" value="{{ cat.title }}"
                                          {% if cat in selected_filters %}checked="checked"{% endif %}>{{ cat.title }}
                        </label></li>
                    {% endfor %}
                </ul>
            </div>
        <button class="filter-button">Применить</button>
        </div>

        <div class="central">
            <div class="block">
                <a class="blue-button" href="{% url 'students:create_student' %}">Добавить</a>


                <select name="sort_option" id="sort-select" class="sort-select">
                    <option value="" {% if sort_option is None %}selected{% endif %}>Сортировать по</option>
                    <option value="inc_year" {% if sort_option == 'inc_year' %}selected{% endif %}>Год по возрастанию
                    </option>
                    <option value="dec_year" {% if sort_option == 'dec_year' %}selected{% endif %}>Год по убыванию
                    </option>
                    <option value="inc_last_name" {% if sort_option == 'inc_last_name' %}selected{% endif %}>Фамилии
                    </option>
                </select>

                <input type="text" name="query" class="search-input" {% if query %} value="{{ query }}" {% endif %}
                       placeholder="Поиск">
                <button class="lupa-button"><img src="{% static 'icons/lupa.png' %}" alt="Изображение" class="lupa">
                </button>

            </div>

            <div class="additional-block">
                <div class="fio">ФИО</div>
                <div class="specialization">Специальность</div>
                <div class="year">Год выпуска</div>
                <div class="year">Редактировать</div>
            </div>

            <div class="additional-blocks">
                {% for student in page_obj %}
                    <div class="additional-block">
                        <div class="fio">{{ student.last_name }} {{ student.first_name }} {{ student.patronymic|default:'' }}</div>
                        <div class="specialization">{{ student.specialization.code }} {{ student.specialization }}</div>
                        <div class="year">{{ student.end_education_date }}</div>
                        <a href="{% url 'students:student' student.id %}"><img src="{% static 'icons/edit-icon.png' %}"
                                                                               alt="Редактировать"
                                                                               class="edit-icon"></a>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="right_table"></div>
    </div>
</form>


{% if page_obj.has_other_pages %}
    <nav class="list-pages">
        <ul>
            {% if page_obj.has_previous %}
                <li class="page-num">
                    <a href="?{{ request.GET.urlencode }}&page={{ page_obj.previous_page_number }}">&lt;</a>
                </li>
            {% endif %}

            {% for p in page_obj.paginator.page_range %}
                {% if page_obj.number == p %}
                    <li class="page-num page-num-selected">{{ p }}</li>
                {% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2 %}
                    <li class="page-num">
                        <a href="?{{ request.GET.urlencode }}&page={{ p }}">{{ p }}</a>
                    </li>
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
                <li class="page-num">
                    <a href="?{{ request.GET.urlencode }}&page={{ page_obj.next_page_number }}">></a>
                </li>
            {% endif %}

        </ul>
    </nav>
{% endif %}

</body>

<script>
    const selectElement = document.querySelector('.sort-select');
    const formElement = document.getElementById('sort-form');

    selectElement.addEventListener('change', function () {
        formElement.submit();
    });
</script>

<script>
    const selectElement = document.getElementById('sort-select');

    selectElement.addEventListener('change', function () {
        const selectedValue = this.value;
        const urlParams = new URLSearchParams(window.location.search);
        urlParams.set('sort-select', selectedValue);
        const newUrl = window.location.pathname + '?' + urlParams.toString();
        window.location.href = newUrl;
    });
</script>
</html>